def runInDocker(String image, Closure body) {
   docker.image(image).inside { body() }
}
@Library('iac-devops-lib') _
pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  parameters {
    booleanParam(name: 'RUN_CD', defaultValue: false, description: 'Ejecutar CD') 
  }   

  environment {
     APP_URL = 'http://localhost:8084/hello'
     //CI_IMAGE = "java-ci-tools:${env.BUILD_NUMBER}"
     MVN_IMAGE =  'maven:3.9.6-eclipse-temurin-17'
     IMAGE_REPO_LOCAL = 'devops_training-java-app'
  }

  stages {
     stage('Info') {
        steps {
          echo "Job: ${env.JOB_NAME}"
          echo "Build: ${env.BUILD_NUMBER}"
          echo "Branch: ${env.BRANCH_NAME}"
        }
     }

     stage('Versioning') {
      steps {
        script {
           //env.IMAGE_VERSION = "1.0.${env.BUILD_NUMBER}"
           env.IMAGE_VERSION = devopsLib.readVersion('VERSION')
           env.VERSION_JAR = "${env.IMAGE_VERSION}-SNAPSHOT"
           env.IMAGE_LOCAL = "${env.IMAGE_REPO_LOCAL}:${env.IMAGE_VERSION}"
           //env.IMAGE_REGISTRY = "${env.REGISTRY_HOST}/${env.REGISTRY_REPO}:${env.IMAGE_VERSION}"
        }
      }
    }
    
    stage('Test') {
      steps {
        script {
           runInDocker(env.MVN_IMAGE) {
             sh 'mvn -version'
             sh 'mvn test'
           }
        }   
      }
    }

    stage('CI - Lint') {
      steps {
         script {
            runInDocker(env.MVN_IMAGE) { 
               sh 'apt-get update && apt-get install -y make'
               sh 'make lint'
            }
         }   
      }
    }
     
    stage('CI - Test') {
      steps {
         script {
            runInDocker(env.MVN_IMAGE) { 
               sh 'apt-get update && apt-get install -y make' 
               sh 'make test'
            }  
         }  
      }
    }
     
    stage('CI - Build image') {
      steps {
        script {
          docker.build(env.IMAGE_LOCAL, "--build-arg VERSION=${env.VERSION_JAR} -f devops/Dockerfile .") 
        }
      }
    }

    stage('CD') {
        when {
          allOf {
            anyOf {
              branch 'develop'
              branch 'main'
            }
            expression { return params.RUN_CD }
          }
        }
        steps {
          script {
            // Definir entorno de despliegue
            echo "CD habilitado: RUN_CD=${params.RUN_CD}, branch=${env.BRANCH_NAME}"  
            env.DEPLOY_ENV = (env.BRANCH_NAME == 'main') ? 'PRO' : 'DEV'
            echo "Deploy env: ${env.DEPLOY_ENV}"
      
            try {
              sh 'docker compose up -d'
              sh 'sleep 5'
              sh 'docker compose logs app'
            } finally {
              sh 'docker compose down --volumes'
            }
          }
        }
        post {
          always {
            echo "Cleanup done"
          }
          success { echo 'SUCCESS' }
          failure { 
             echo 'FAILURE' 
             sh 'docker compose logs || true'
          }
        }
      }
  }
}
