name: CI-CD

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - develop
      - master

  workflow_dispatch:
    inputs:
      RUN_CD:
        description: 'Run Continuous Deployment'
        required: false
        default: false
        type: boolean

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mostrar contexto
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Ref:  $GITHUB_REF"
          echo "Branch: $GITHUB_REF_NAME"
          echo "RUN_CD: ${{ inputs.RUN_CD }}"

  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.RUN_CD == true }}
    steps:
      - name: Deploy
        run: echo "🚀 Ejecutando CD..."
