name: CI-CD

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - develop
      - master

  workflow_dispatch:
    inputs:
     #definimos el parámetro de codición para ejecutar o no el job CD
      RUN_CD:
        description: 'Run Continuous Deployment'
        required: false
        default: false
        type: boolean
env:
  # Variables de entorno globales:
  IMAGE_NAME: "scalian_training-java-app"
  APP_URL: "http://localhost:8084/hello"
jobs:
  ci:
    # nombre que veremos del job
    name: Continuous Integration
    runs-on: ubuntu-latest
    # definición de los diferentes pasos del job
    steps:
      # Descarga el código del repositorio dentro de la máquina virtual.
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Mostrar contexto
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Ref:  $GITHUB_REF"
          echo "Branch: $GITHUB_REF_NAME"
          echo "RUN_CD: ${{ inputs.RUN_CD }}"
      - name: Usando variables en shell
        run: |
          echo "Image: $IMAGE_NAME"
          echo "App URL: $APP_URL"   

  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.RUN_CD == true }}
    steps:
      - name: Deploy
        run: echo "🚀 Ejecutando CD..."
