trigger:
  branches:
    include:
      - develop
      - main
pr:
  branches:
    include:
      - develop
      - main

resources:
  repositories:
    - repository: iac
      type: github
      name: jtomaschico/devops-training-iac-devops
      ref: refs/heads/feat/base
      endpoint: jtomaschico

variables:
  - group: josetoCredentials
  - name: IMAGE_NAME
    value: "myapp"  # Asegúrate de definir un nombre adecuado para la imagen Docker
  - name: APP_URL
    value: "your-app-url"  # Define tu URL de aplicación o cualquier otra variable relevante

parameters:
  - name: RUN_CD
    type: boolean
    default: false
    displayName: "Run Continuous Deployment"

  - name: DEPLOY_ENV
    type: string
    default: DEV
    displayName: "Deployment Environment"

pool:
  name: Default   # Self-hosted agent

stages:
  - stage: CI
    displayName: "Continuous Integration"
    jobs:
      - job: Info
        displayName: "Info devops-training-java-app"
        steps:
          - script: |
              echo "Repo:   $(Build.Repository.Name)"
              echo "Branch: $(Build.SourceBranchName)"
              echo "SHA:    $(Build.SourceVersion)"
              echo "Reason: $(Build.Reason)"
              echo "IMAGE: $(IMAGE_NAME)"
              echo "URL:   $(APP_URL)"
            displayName: "Show Info"

      - job: CI_Template
        displayName: "CI Java (template)"
        steps:
          - template: azure-pipelines/templates/ci-java-steps.yml@iac

      #- job: build_image
       # displayName: "Build image"
        #dependsOn: CI_Template
        #steps:
         # - checkout: self
          #- script: |
           #   docker build -t $IMAGE_NAME:latest -f devops/Dockerfile .
            #displayName: "Docker build"   

      # Paso para construir la imagen Docker usando maven:3.8.6-openjdk-11-slim
      - job: Build_Docker_Image
        displayName: "Build Docker Image"
        dependsOn: CI_Template
        steps:
          - checkout: self
          #- script: |
           #   echo "Build with Maven container..."
            #  docker run --rm \
             #   -v "$(Build.SourcesDirectory)":/workspace \
              #  -w /workspace \
               # --user root \
                #maven:3.8.6-openjdk-11-slim \
                #bash -c "
                 # apt-get update && \
                #apt-get install -y sudo curl bash make && \
                  #curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
                  #apt-get install -y nodejs && \
                  #node -v && npm -v"
            #displayName: "Build with Maven container"
          - script: |
              echo "Instalando Node.js y dependencias..."
              sudo apt-get update
              sudo apt-get install -y curl bash make nodejs npm
              node -v
              npm -v
            displayName: "Instalar dependencias en el agente"  
          - script: |
              echo "Building Docker image..."
              #docker build -t $(IMAGE_NAME):latest -f devops/Dockerfile .
              docker build -t $(IMAGE_NAME):$(Build.BuildId) -t $(IMAGE_NAME):latest .
            displayName: "Docker Build"  

          
  - stage: CD
    displayName: "Continuous Deployment"
    dependsOn: CI
    condition: eq('${{ parameters.RUN_CD }}', true)
    jobs:
      - job: CD
        displayName: "Continuous Deployment"
        steps:
          - script: |
              echo "🚀 Desplegando aplicación..."
              echo "Entorno de despliegue: ${{ parameters.DEPLOY_ENV }}"
            displayName: "CD Steps"
