trigger:
  branches:
    include:
      - develop
      - main
pr:
  branches:
    include:
      - develop
      - main

resources:
  repositories:
    - repository: iac
      type: github
      name: jtomaschico/devops-training-iac-devops
      ref: refs/heads/feat/base
      endpoint: jtomaschico

variables:
  - group: josetoCredentials

parameters:
  - name: RUN_CD
    type: boolean
    default: false
    displayName: "Run Continuous Deployment"

  - name: DEPLOY_ENV
    type: string
    default: DEV
    displayName: "Deployment Environment"

pool:
  name: Default   # Self-hosted agent

stages:
  - stage: CI
    displayName: "Continuous Integration"
    jobs:
      - job: Info
        displayName: "Info devops-training-java-app"
        steps:
          - script: |
              echo "Repo:   $(Build.Repository.Name)"
              echo "Branch: $(Build.SourceBranchName)"
              echo "SHA:    $(Build.SourceVersion)"
              echo "Reason: $(Build.Reason)"
              echo "IMAGE: $(IMAGE_NAME)"
              echo "URL:   $(APP_URL)"
            displayName: "Show Info"

      - job: CI_Template
        displayName: "CI Java (template)"
        steps:
          - template: azure-pipelines/templates/ci-java-steps.yml@iac 


  - stage: CD
    displayName: "Continuous Deployment"
    dependsOn: CI
    condition: eq('${{ parameters.RUN_CD }}', true)
    jobs:
      - job: CD
        displayName: "Continuous Deployment"
        steps:
          - script: |
              echo "🚀 Desplegando aplicación..."
              echo "Entorno de despliegue: ${{ parameters.DEPLOY_ENV }}"
            displayName: "CD Steps"
